### ISSUE TITLE
OpenJFX for 8u121

### ISSUE THREAD

**Issue by mokun** [SkyLandTW/OpenJFX-binary-windows#1]
Thanks much for posting OpenJFX 8u60. It's been a year ago though.

I'm on windows platform and have been trying to set up OpenJDK and OpenJFX together.

I can't find OpenJDK 8u60 to match up with OpenJFX for 8u60. My application won't run, even after I resort to using a few versions of OpenJDK. 

Can we have the latest and greatest OpenJFX for 8u121 for windows ?

Appreciate!

**Comment by jiping-s** [comment]
Hello! There appears to be no new release of OpenJFX after 8u60, see http://hg.openjdk.java.net/openjfx

8u60 is for API change, 8u121 should contain only fixes and patches. I verified JavaFX samples and our own apps on OpenJDK 8u112 build from zulu is still okay.

However, my build does not contain the whole web browser core as their included webkit is too difficult to build on windows. Anything depending on HTML rendering cannot run.

**Comment by jiping-s** [comment]
I was wrong. There are indeed updates in jfx, http://hg.openjdk.java.net/openjfx/8u-dev/rt

will try to build with webkit.

**Comment by jiping-s** [comment]
Done. The new build is for 8u172-b11. If you need specific versions, just follow the steps in my *README.md*.

**Comment by mokun** [comment]
Thanks much. I'll try to compile later. Meanwhile, do you mind you posting your OpenJFX windows binaries in github for me to download and quickly test it ?

**Comment by jiping-s** [comment]
It's already in the release: https://github.com/SkyLandTW/OpenJFX-binary-windows/releases
